### ISSUE TITLE
Add constant label or annotation in jiva PVCs for uniqueness

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#1321]
## FEATURE REQUEST
 
 

**What happened**:
Not able to sort OpenEBS PVCs among given pods in the MayaView.

**What you expected to happen**:
In MayaView, we want to filter OpenEBS PVC pods from all the pods in the system. We want to sort based on label or unique annotation.

**Comment by sagarkrsd** [comment]
We need a label or a unique annotation so that we can filter OpenEBS PVC pods (controllers or services) from others displayed in scope based on that unique label or annotation.
It would be better to have a common label or annotation for all of these resources so that using a single label or annotation, we can filter out the OpenEBS PVC pods (controllers and services) from the others.

**Comment by kmova** [comment]
PVC objects themself are user created, we may not have an option to modify those. However, using the storageclass associated with the PVC we can determine if they belong to OpenEBS. 

PVC Pods and other K8s objects need to be labelled. This will be implemented as part of the issue
https://github.com/openebs/openebs/issues/203
