### ISSUE TITLE
Fix golint issue in volume.go

### ISSUE THREAD

**Issue by Akash4927** [openebs/openebs#1955]
File: [volume.go](https://github.com/openebs/maya/blob/master/pkg/volume/volume.go)

```
Line 205: warning: exported method VolumeOperation.Delete should have comment or be unexported (golint)
Line 365: warning: exported method VolumeListOperation.List should have comment or be unexported (golint)
```

**Comment by albertogviana** [comment]
I will take this one.

**Comment by ashishranjan738** [comment]
sure @albertogviana go ahead

**Comment by albertogviana** [comment]
Hi, 

I fixed the https://github.com/openebs/maya/pull/585 issue, and in the time that I was waiting for the build, I also fixed this issue. However I pushed my code to my fork and when I realized my code was running together with the 585 issue. So this issue was fixed with the 585 issue, I am sorry for the inconvenience.
