### ISSUE TITLE
Unable to bring up the minions: Stuck on 'Using Token'

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#218]
Scenario: Trying to get openebs/k8s/vagrant/1.7 setup

Result:
- kubemaster-01 was up & running
- kubeminion-01 was stuck with below message

```
==> kubeminion-01: Using Master IP  - 172.28.128.3
==> kubeminion-01: Using Token -  bdb573.063666e8dded3776
```

**Comment by AmitKumarDas** [comment]
I did two things to get the setup up & working:

1. edited the Vagrantfile to ensure 2048 memory & 2 CPUs to each minion
2. destroyed the earlier kubemaster-01 vagrant VM

NOTE - The kubemaster-01 was getting created easily. However, the kubeminion-01 was getting stuck with above message.

**Comment by kmova** [comment]
Related issue -  https://github.com/kubernetes/kubeadm/issues/335

**Comment by victorr** [comment]
I reproduced the problem with a fresh checkout and giving the minions 2048 MB of memory:

    KH_MEM=2048 vagrant up

Vagrant got stuck:
```
==> kubeminion-01: Getting the Master IP and Token to join the cluster...
Connection to 127.0.0.1 closed.
Connection to 127.0.0.1 closed.
Connection to 127.0.0.1 closed.
Connection to 127.0.0.1 closed.
==> kubeminion-01: Using Master IP  - 172.28.128.3
==> kubeminion-01: Using Token -  64666c.5d84cf2ba5d4ea5a
```
I verified in the VirtualBox GUI that the minion had 2048 MB of memory and 2 CPUs.

**Comment by AmitKumarDas** [comment]
@victorr A fresh checkout means there were no stale VMs ?

**Comment by ksatchit** [comment]
Couple of observations: 

- This seems to have been fixed by https://github.com/kubernetes/kubernetes/pull/48480. So please try with later version of the vagrantfiles (1.8.2>) 

- All the vagrantfiles have a 2GB memory for master & 1GB memory for nodes. It is commonly observed that the bring-up OR subsequent deployments/load fails with this configuration. The minimum memory allocated for the nodes should be 2GB. This needs to be changed in:

  - The vagrantfiles here: https://github.com/openebs/openebs/tree/master/k8s/vagrant
  - The vagrantfile creation script/templates here: https://github.com/openebs/openebs/tree/master/k8s/lib/vagrant

**Comment by mahebbar** [comment]
Documented at https://staging-docs.openebs.io/docs/next/tsg_install.html#KubeminionError
