### ISSUE TITLE
Design for less-performance impact deduplication in ZFS

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2181]
De-deduplication provides storage savings, more than compression, in certain workloads/scenarios. At the same time, enabling de-duplication will have performance impact in ZFS.

ZFS does inline deduplication. It also stores the deduplication table as ZAP objects on the disk. Walking through on-disk multi-level hash table will be very time consuming.

This issue is created to have, a design for less-performance impact deduplicaiton in zfs, by:
- bringing in different other approaches for de-duplication
- listing down the constraints / requirements / pros and cons of each approach
- having high-level design considering all the scenarios (and low-level design as well if the approach is promising)

**Comment by richardelling** [comment]
The historical reasons for slow ZFS dedup performance are:

- sha256 checksums instead of the less-CPU-intensive fletcher4
- HDD pools have poor IOPS

In the current 0.8-rc ZoL the response time of HDD problem is largely solved by special metadata classes. Also, faster checksum algorithms are available.

However, those will not reduce the problem of the number of objects possible in PB-sized pools. Several solutions have been proposed over the years, but none solve the number of objects completely.

See also https://storageswiss.com/2018/10/17/is-all-flash-deduplication-a-must-have/

**Comment by vishnuitta** [comment]
Thanks @richardelling for sharing your thoughts.
Link you shared makes totally sense. Thanks.
