### ISSUE TITLE
Can I use create NFS Server  on jiva pool ? I Does not require high performance

### ISSUE THREAD

**Issue by dingsongjie** [openebs/openebs#2751]
I just want add some pictures and zips in NFS Server ,does not require high performance.

**Comment by ranjithwingrider** [comment]
Hi @dingsongjie . Thanks for choosing OpenEBS for your particular use-case.
Yes, NFS server can be created on Jiva. We have written one document for cStor as OpenEBS volume. By changing the StorageClass mentioned for cStor with Jiva StorageClass, you can achieve this particular use case.
This is the reference doc : https://docs.openebs.io/docs/next/rwm.html

Note: Skip the `select or create cStor pool` and mention Jiva StorageClass name instead of cStor StorageClass. Let me know if any more information is needed.

**Comment by dingsongjie** [comment]
> Hi @dingsongjie . Thanks for choosing OpenEBS for your particular use-case.
> Yes, NFS server can be created on Jiva. We have written one document for cStor as OpenEBS volume. By changing the StorageClass mentioned for cStor with Jiva StorageClass, you can achieve this particular use case.
> This is the reference doc : https://docs.openebs.io/docs/next/rwm.html
> 
> Note: Skip the `select or create cStor pool` and mention Jiva StorageClass name instead of cStor StorageClass. Let me know if any more information is needed.

Thank you for your reply ，I would try this

**Comment by dingsongjie** [comment]
It works fine ,thank you again !
