### ISSUE TITLE
Add support to disable over provisioning on cStor Pools

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2855]
## Description

It was observed in some cases that even though the application only effectively writes about 5GB of data, the underlying pool shows more than 50GB used. Sometimes the pool can be 100% full after which the pool stops serving IO causing the applications to fail. 

## Context
Over provisioning is enabled by default on cStor volumes. Example, users will be able to create a volume of 200GB on cStor Pool with disk capacity of 100G. This allows for cases where user can save cost on the underlying storage spend and increase the capacity of the pools by adding more disks or expanding the disks, as volume starts consuming the space. 

The usage can be monitored by looking at the volume and pool metrics. 

While the above is applicable for the write-intensive workloads like Elastic, the workloads like postgresql that will potentially modify the existing blocks can end up quickly consuming more space from the pool. 

In case of postgres, that typically installs Ext4 on top of the cstor volumes will result in the following:
- Ext4 is mounted without unmap support
- As data is written and modified, Ext4 tends to use new blocks of storage - without sending any delete (unmap) requests back to the underlying block storage - like cStor. 
- As the volumes are over provisioned, cStor keeps allocating new blocks from the pool. 

This will result in a case where the application would have effectively used only 3GB of data on ext4, but about 100GB of data is already utilized in the pool because volume (ext4) quota is set at 200GB. 

## Workaround
Enable storage class based resource quota to set a limit on the sum of capacity allocated to all the PVCs to be within the available capacity of the underlying cStor Pools. https://kubernetes.io/docs/concepts/policy/resource-quotas/#enabling-resource-quota

## Possible solution
* Provide an option at the cStor Storage Class to disable over provisioning

**Comment by vishnuitta** [comment]
disabling thin provisioning may sound like solves this issue, but, user faces errors during provisioning time.. it should be part of best practices for user to look at pool usage and take necessary actions.
unmap is worth to have but this will be useful in the cases when user anticipated volume size wrongly with workloads that does writes and deletes (like above)

**Comment by vishnuitta** [comment]
When pool becomes full, cstor-pool container crashes continuously. This ends up in OS disk space consumption to store cores.
This PR https://github.com/openebs/cstor/pull/282 disables dumping core by default.

**Comment by vishnuitta** [comment]
request made in this issue https://github.com/openebs/openebs/issues/2673 is to disable thin provisioning, which is same as this issue

**Comment by sonasingh46** [comment]
The overprovisioning feature has not yet made into the CSPC based pools. Reopening the issue to track that.

**Comment by kmova** [comment]
Groom and take a call on this issue.

**Comment by sonasingh46** [comment]
The initial idea on this was to have a delayed binding for CVR by a new cvr controller that is basically a constraint-based storage scheduler : 
We need to have a separate controller(let us say this as cvr-scheduler as of now) that watches for CVR. Once the CVR is created, it is unassigned, meaning it does not belong to any CSPI. Now, this cvr-scheduler enforces policies and requirements e.g. overprovisioning etc and picks up appropriate or most suitable CSPI for the particular CVR and assigns this CVR to a CSPI by patching the CVR. This patching will basically put the selected CSPI name and UUID on the CVR. 

Now, the actual cvr-operator ( replica controller ) -- also watches for the CVRs. It ignores the CVR that has not been assigned any CSPI. Once the CVR is assigned to a CSPI, the replica controller processes the CVR to carry out the volume provisioning. 

The advantages of this approach are as follows : 
- Volume replica distribution is achieved easily and users can specify a variety of policies or enforcements to have the CVRs assigned to the most suitable CSPI. ( e.g. overprovisioning is just a policy that can be optionally enforced )
- Incremental policies can just be added to the cvr-scheduler and this new controller as this sole responsibility of just scheduling the CVR to a CSPI. [Sepration of concerns] This can drastically improve the development time as a developer will not need to worry about the hidden complexities involved in the replica controller. 
- There will be an option to bypass the cvr-scheduler in case there is a requirement for quick scheduling for use cases where software need to create volumes on demand. For example, software that launches workspace for users ( e.g. gitpod, hackerrank, etc ). The volume provisioning should be quick in this case so that the user has instantly an IDE/workspace ready.
If the scheduler is bypassed, the CVR will be bind to the CSPI by the current way it is binding.
