### ISSUE TITLE
Old snapshots are still available inside pool even though the schedule is for 10 days.

### ISSUE THREAD

**Issue by ChandanSagar** [openebs/openebs#2957]
## Description
In a setup, for a volume of 1G, replicas are of size 70G.. going further found that, there are local snapshots available on the pool since 2019 Aug even though the retention policy of velero schedule is just 10 days (240 hours). Also, when the data is backed up to a remote place like velero/Minio, why local snapshot is left out?

## Expected Behavior
Snapshots should be cleared after the schedule is over. Also, snapshots should be cleared locally after pushing them into a remote place. 

## Current Behavior
Snapshot remains in the setup even after the schedule is over and pushed to a remote place.

**Comment by mynktl** [comment]
Maya-apiserver doesn't have support to disable snapshot.

Just listing out the expected behavior...
1. **when velero-plugin receives snapshot deletion request**
- plugin should delete the remote backup files and send the request to maya-apiserver for `cstorbackup` deletion.
- maya-apiserver should delete relevant snapshot and `cstorbackup` for given backup and update `CStorCompletedBackups` accordingly.
- if backup is not part of schedule then maya-apiserver should also delete `CStorCompletedBackups` for the given backup.

2. **When backup completes**
- maya-apiserver should delete relevant snapshot and `cstorbackup`, CStorCompletedBackups for given backup, if backup is not part of schedule.
- if backup is part of schedule then maya-apiserver should delete the snapshot(and `cstorbackup`), if snapshot is not generated by the last **completed** backup and update the relevant `CStorCompletedBackups` accordingly.
cc: @vishnuitta

**Comment by vishnuitta** [comment]
thanks @mynktl for the steps..
let us just implement the '2nd' one i.e., when backup completes (be it either succeeds or fails).. Lets us not worry about '1st' one.
So, with this, we can still have last and last but one snapshots on cstor pool, and, admin need to manually delete them when deleting the velero backup schedule. It can be documented.

**Comment by kmova** [comment]
Few more dependent PRs need to be merged.
