### ISSUE TITLE
jivactl info showing two childs for a meta file

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2965]
In some scenarios with replica pods restarting, jivactl info showed two children for a metafile. 

One possible way to hit this issue is:
- head and metafile creation are in progress on replica
- replica restarted

Having two children is not an issue for data/IO, but can cause issues with management functions like snapshot delete.  This could be potentially fixed by making sure the chain only traverses the path through volume.meta.

**Comment by utkarshmani1997** [comment]
Two child is not an issue rather it's part of design, it's useful in snapshot revert, apart from this there can be situations where we can have two children:
- When snapshot is not deleted from all the replicas
- When rebuild is done partially on degraded replica and it becomes healthy due to same revision count

In above case a stale snapshot remains causing two children. From data perspective it's not an issue since chain remain intact.
