### ISSUE TITLE
Enhancements to mayactl for Jiva volumes 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2969]
This is a feature request to display the size (du -h) of each replica in the `mayactl volume info/stats` commands. 

It will be good to implement this for both jiva and cstor.

**Comment by utkarshmani1997** [comment]
Current implementation of mayactl is broken for snapshot related queries. I have tested following commands and it didn't work for me:
```
bash-4.3# mayactl snapshot create --volname=pvc-9babeb43-96aa-4da2-b8d4-e142b3a1efda --snapname=hello -n openebs
Executing volume snapshot create...
Snapshot creation failed: failed to create snapshot 'hello': missing volume name
bash-4.3# mayactl snapshot list
--volname is missing. Please specify an unique name
bash-4.3# mayactl snapshot list --volname=pvc-9babeb43-96aa-4da2-b8d4-e142b3a1efda
Error list available snapshot: Server status error: Bad Request
```
both commands failed with different errors. Further digging into the logs of maya-apiserver i found out that namespace related checks are not there for all the snapshots. I also tried to hit the endpoint using curl and this gave me different error:
```
bash-4.3# curl "10.96.219.5:5656/latest/snapshots/?volume=pvc-9babeb43-96aa-4da2-b8d4-e142b3a1efda&namespace=openebs"
unable to list snapshots: missing cas template for list snapshot
```
I quickly had a look at the code and i found that snapshot list related CAS Template is not there. As of now all the snapshot related commands have been commented out in the mayactl.

Since jiva already provides `jivactl` a command line tool to manage jiva volumes, snapshot related functionality is already there. One can run following command to query about the snapshot by execing into the controller.

- `jivactl ls`
- `jivactl snapshot ls`
- `jivactl snapshot info`
