### ISSUE TITLE
replicaCount not getting updated in cvc after scaling up the volume replicas.

### ISSUE THREAD

**Issue by gprasath** [openebs/openebs#2977]
## Description
- The field replicaCount in cvc is not getting updated after scaling up the volume replicas.

## Expected Behavior
- Once the volume replicas are scaled up successfully, the replicaCount should also be increased.

## Current Behavior
- It remains static.

## Steps to Reproduce
- Provision a cStor volume with single replica.
- Ensure that the volume is created successfully.
- Check the replica count in its respective cvc.
- Scale up the volume replica by adding pool name under spec.policy.replicaPoolInfo.
- Ensure that the volume is scaled up successfully.
- Now, check the replica count. It is not increased.

**Comment by mittachaitu** [comment]
It is expected behaviour but from usability wise it's should not remain with the same value. Since the field replicaCount  is under spec it shouldn't be updated by controller.  So if we ask to increase replica count for scaleUp then default assumption will be decreasing replica count should decrease should perform scale down. Since scale down is related to removing the data it shouldn't perform as an automated way(Good to take Input from the user).
So to avoid this confusion we are moving replicaCount under `provision` in CVC(
https://github.com/openebs/api/pull/30/files#diff-ea079ae37e880b2e827aaee56cfac9bf)
