### ISSUE TITLE
enable execution of test cases for openebs/istgt arm image in travis

### ISSUE THREAD

**Issue by shubham14bajpai** [openebs/openebs#2988]
We have enabled arm builds for openebs/istgt (openebs/istgt#310)
Due to some limitation in travis we have disabled the test case execution for arm images in travis.

**Comment by mittachaitu** [comment]
As part of testing in ARM, machine figured out following test cases need fixes:
- `data_integrity_with_unknown_replica`: Test is failing because of timing issue mainly md5sum calculation is taking a long time meanwhile non-quorum replicas became healthy and the test is expecting non-quorum replicas to be a degraded state(Because of this test is failing).

- `run_io_timeout_test`: Test is failing because of output formatting issue with `ioping` command. In ubuntu18.04 ioping on particual device is reporting output in nanoseconds(but man pages are saying output will be in microseconds) to fix we calculated latency using 10^9. In ARM machines(aarch64) ioping is giving output in microseconds since we are using 10^9 calculation went wrong and test is failing.

- `run_test_env`: In ARM machines following command `QueueDepth=5 Luworkers=9 /usr/local/bin/istgt -R 20` is not seting QueueDepth and Luworkers envs and test is expecting same values due to this `run_test_env` is failing.
