### ISSUE TITLE
[cstor-csi]:  Application went to RO state on performing network loss on target container (istgt) 

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#3108]
## Description
- While performing the network loss on cstor target istgt container seeing that application pod continuously went into crashloopbackoff state after removed the network loss rule. Looking upon the application mount point it's in `RO` state.  Even if we restart the application pod still it went to crashloopbackoff because of mount point is still RO.

**Note**: When the application is scheduling on the same node then this behaviour is observed.

## Expected Behaviour
- Application pod has to be run after removed the network loss from istgt container.

## Current Behaviour
- Application pod keeps on crashing and the  volume mount is in ro state
```
k8s@e2e1-node3:~$ mount | grep pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369
/dev/sdf on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369/globalmount type ext4 (ro,relatime,stripe=256)
/dev/sdf on /var/lib/kubelet/pods/afdc8803-7030-46c0-82c8-156b5d2c4525/volumes/kubernetes.io~csi/pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369/mount type ext4 (ro,relatime,stripe=256)
```
```
k8s@e2e1-master:~/e2e-tests$ kubectl get po -n percona
NAME                      READY   STATUS             RESTARTS   AGE
percona-f445994bd-sj4s6   0/1     CrashLoopBackOff   6          7m25s
tpcc-bench-kr6kt          0/1     Completed          0          31m
k8s@e2e1-master:~/e2e-tests$ kubectl get pvc -n percona
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS              AGE
testclaim   Bound    pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369   5Gi        RWO            openebs-cstor-cspc-disk   40m
k8s@e2e1-master:~/e2e-tests$ kubectl get cv -n openebs
NAME                                       CAPACITY   STATUS    AGE
pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369   5Gi        Healthy   40m
k8s@e2e1-master:~/e2e-tests$ kubectl get cvr -n openebs
NAME                                                                 ALLOCATED   USED   STATUS    AGE
pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369-cstor-cspc-disk-pool-49gh   164M        368M   Healthy   40m
pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369-cstor-cspc-disk-pool-mtn4   164M        368M   Healthy   40m
pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369-cstor-cspc-disk-pool-nrpj   164M        368M   Healthy   40m
```
## Steps to Reproduce
- Deploy application with liveness probe enabled
- perform network loss on cstor istgt container using tc `tc qdisc add dev eth0 root netem loss 100.00`
- wait for ~240s and remove the network loss rule `tc qdisc del dev eth0 root netem loss 100.00`
- check the application status it's in crashloopbackoff state.

[istgt-container-log](https://github.com/openebs/openebs/files/5089535/istgt-container.log)
[cstor-csi-plugin-log](https://github.com/openebs/openebs/files/5089536/node3-cstor-plugin.log)

**Comment by mittachaitu** [comment]
**Explanation**:
This behavior is observed when the application pod is scheduled on the same node upon the deletion of the pod. When the application is scheduling on the same node `CSI CO` sends only `NodePublish` and `NodeUnpublish` request. To serve those requests CSI-Node plugin will perform `Unmount` and `bind mount` on target path not on the staging path. Since unmount and mount performed on `targetPath` application mount not able to mark as RW.

**Target path**: From path where the application pod will consumes the volume `/var/lib/kubelet/pods/afdc8803-7030-46c0-82c8-156b5d2c4525/volumes/kubernetes.io~csi/pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369/mount`.
**Staging path**: GlobalMounting path from here different applications(consuming this volume) will --bind mount to their own path(Path looks like: `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-cf7a7f51-39e9-4347-bb9b-3c20f3d7a369/globalmount` ).

**Possible Workarounds**: 
- Scaledown the application and Scaleup the application.
                            (Or)
- Enforce the application pod to move to a different node.
                            (Or)
- Enable the `REMOUNT` feature in CSI node daemonset.

**Comment by kmova** [comment]
Can the remount feature be enabled by default though kubectl and helm charts.

**Comment by mittachaitu** [comment]
In recent releases(2.4 I think), `REMOUNT` feature is enabled in both the installation process via [Helm charts](https://github.com/openebs/cstor-operators/blob/e4eed0d2764823746cc7021c641b9e81f8d8ed76/deploy/helm/charts/values.yaml#L162) as well as [operator](https://github.com/openebs/charts/blob/gh-pages/2.9.0/cstor-operator.yaml#L1393-L1394) way.

**Comment by mittachaitu** [comment]
REMOUNT feature was enabled by default in the following versions and PRs
- 2.4.0 version of cStor-operator in [openebs/charts#191](https://github.com/openebs/charts/pull/191) PR. 
- 2.5.0 version of helm charts in [openebs/cstor-operators#180](https://github.com/openebs/cstor-operators/pull/180/files) PR
