### ISSUE TITLE
Openebs For Windows support

### ISSUE THREAD

**Issue by Sabarish41** [openebs/openebs#3300]
Hello Team,

Could you please help me on whether Openebs can support windows environments.
If not let me know if I can atleast do a PVC claim from windows node to linux master.

Regards,
Sabarish S S

**Comment by kmova** [comment]
cc: @nconnolly1 - who is helping with some of the activities around enabling CAS for windows.

**Comment by Mohkam** [comment]
maybe something like CSIProxy would be great since windows worker nodes do not support `privileged containers`.  I hope OpenEBS will address windows containers sooner.

**Comment by Sabarish41** [comment]
Hello Team,

Hope you guys are doing well.
Please let me know if the latest release has Windows acceptance policy so that we can go ahead and use the solution.

Regards,
Sabarish S S

**Comment by nconnolly1** [comment]
Supporting CSI on Windows requires CSI Proxy (https://github.com/kubernetes-csi/csi-proxy) which is currently in Alpha. The proxy provides a way for a CSI Node Plugin to perform privileged operations on Windows (where there is no support for privileged containers). It does this through a set of gRPC APIs implemented over named pipes, which means that existing CSI Node Plugins need to be refactored in order to support Windows. This is described in the Kubernetes Enhancement Proposal for CSI Proxy (https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1122-windows-csi-support). The KEP says that the details around the refactoring 'will be documented in a plugin developer guide', but this doesn't appear to have been written yet. The kubernetes/utils/mount package (https://github.com/kubernetes/utils/tree/master/mount) seems to contain support for the CSI Proxy.

In order to work with Windows, the OpenEBS CStor CSI Driver will need to be refactored to use the gRPC APIs provided by CSI Proxy.

**Comment by vmasule** [comment]
Hi @nconnolly1,

> In order to work with Windows, the OpenEBS CStor CSI Driver will need to be refactored to use the gRPC APIs provided by CSI Proxy.

Is this implementation done? We are using CSIProxy without any issues but we need a support for Distributed file system on our windows nodes.

Please confirm. Thanks.

**Comment by nconnolly1** [comment]
Hi @vmasule - as far as I am aware no-one is working on Windows CSI support at the moment. I would suggest asking in the CNCF openebs slack channel to see if anyone has a similar interest and whether they are working on any code. Failing that, we'd love you to contribute to the project if you are able to prepare a PR yourself.
