### ISSUE TITLE
Openebs volume allows to write data of size more then the available physical capacity of pools.

### ISSUE THREAD

**Issue by jj-2020** [openebs/openebs#3377]
### **Description**
We were trying out openebs to utilize kubenode disks as kubernetes storage, however while creating PVC, we observed that openebs was allowing provisioning of storage beyond the capacity of underlying nodes. Also, we were able to fill it up using fallocate.

### **Current Behaviour**
_kubectl get bd_
NAME                  NODENAME     SIZE         CLAIMSTATE   STATUS     AGE
blockdevice-1...   kubenode03   17178803712     Claimed      Active     17h
blockdevice-2...   kubenode01   17178803712     Claimed      Active     17h

NDM identifed disks of 16GB from two nodes

**_Capacity of underlying nodes-_**
![storage](https://user-images.githubusercontent.com/82487271/114657309-6b951480-9d0d-11eb-9f3d-e210f3386627.png)
As shown in the above image, Hard disk 5 is the raw disk created for kubernetes storage (to be used with openebs)

We created pvc with storage request of 1Ti, with storage class linked to the storagepoolclaim having the above blockdevices.
**PVC provisioned-**
_kubectl get pvc_
NAME                    STATUS   VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS      AGE
testapp-pvc-testapp-0   Bound    pvc-...   **1Ti**        RWO            openebs-cstor-1   14h
testapp-pvc-testapp-1   Bound    pvc-...   **1Ti**        RWO            openebs-cstor-1   14h
testapp-pvc-testapp-2   Bound    pvc-...   **1Ti**        RWO            openebs-cstor-1   14h

**To our surprise we were able to fill the pv with few files via fallocate (at the pvc mountpoint)-**

[testapp-0 test]$ ls -lh
total 401G
-rw-r--r--. 1 root  root   10 Apr 13 13:47 host
drwxrws---. 2 root  root  16K Apr 13 13:46 lost+found
-rw-rw-r--. 1 root  root 400G Apr 13 13:47 test_1
-rw-rw-r--. 1 root  root 400G Apr 13 13:48 test_2
-rw-rw-r--. 1 root  root 100G Apr 13 13:49 test_3

**Also checking on the node, we found the below results. Note: sdf is the block device identified by NDM-**
sde                                                                                            8:64   0    1T  0 disk /var/lib/kubelet/pods/9d.../volumes/kubernetes.io~iscs
sdf                                                                                            8:80   0   16G  0 disk 
└─sdf1                                                                                         8:81   0   16G  0 part 

Utilization on node via du-
_du -sh /var/lib/kubelet/pods/9d.../volumes_
901G	/var/lib/kubelet/pods/9d.../volumes

Utilization reported by openebs-
_kubectl get cstorpool_
NAME                 ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE      AGE
cstor-disk-pool-1    18.3M       15.9G   15.9G      Healthy   false      striped   17h
cstor-disk-pool-1    7.62M       15.9G   15.9G      Healthy   false      striped   17h

### Concerns-
1- Openebs volume allows to write data of size more than the available physical capacity of pools.
2- We found that the usage reported via openebs, does not match the actual usage (Refer the above output of kubectl get cstorpool).

**Comment by jj-2020** [comment]
Thank you @mittachaitu for guiding us to the thickprovisioning parameter.
Below is the data as requested (we had to reproduce the above scenario in a new cluster). We have divided it into 2 sections, first one with data of sparse files and another one with non-sparse files-

Section-1

**Is load really generated the load? (Or) Do you create the sparse files?**
Yes, we are using the below commands to generate the files inside the pod-
fallocate -l +400G test_1
fallocate -l +400G test_2
fallocate -l +100G test_3

**Output of kubectl get cvr -A**
[~]# kubectl get cvr -A
NAME      USED   ALLOCATED   STATUS    AGE
pvc-...   217M   5.85M       Healthy   27m
pvc-...   258M   5.95M       Healthy   27m


**Output of kubectl get pv**

[~]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                           STORAGECLASS      REASON   AGE
pvc-...  1Ti        RWO            Delete           Bound    default/testapp-pvc-testapp-1   openebs-cstor-1            28m
pvc-...  1Ti        RWO            Delete           Bound    default/testapp-pvc-testapp-0   openebs-cstor-1            29m


**Can you share du -sh running inside the container?**
Below is the output from the mount point inside the container-
[~]$ du -sh /home/app/test/
901G	/home/app/test/

**Section-2 (With non-sparse file)**

**Is load really generated the load? (Or) Do you create the sparse files?**
Copied /var/log/messages file (2.2G) to the pod-
for i in {1..30};do kubectl cp /var/log/messages testapp-0-...:/home/app/test/messages_$i;done

**Output of kubectl get csp -A**

[~]# kubectl get csp -A
NAME                     ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE      AGE
cstor-disk-pool-1-...   14.1G       1.80G   15.9G      Healthy   true       striped   50m
cstor-disk-pool-1-...   6.59M       15.9G   15.9G      Healthy   false      striped   50m

Output of kubectl get cvr -A
[~]# kubectl get cvr
NAME      USED    ALLOCATED   STATUS    AGE
pvc-...   46.9G   14.1G       Offline   40m
pvc-...   71.0M   5.27M       Healthy   40m


**Can you share du -sh running inside the container?**
Below is the output from the mount point of container-
[~]$ du -sh /home/app/test
54G	.

**Apart from this we have few more queries regarding the above scenarios-**

1- Is there any document that we can refer, for the thick provisioning parameter in openebs? 

2- We saw in the case of thick-provisioning and non-sparse files, the volume becomes read-only even though there is 1.80G free-
[~]# kubectl get csp
NAME                     ALLOCATED   FREE    CAPACITY   STATUS    READONLY   TYPE      AGE
cstor-disk-pool-1-...   14.1G       **1.80G**   15.9G      Healthy   true       striped   52m

Is cstor reserving space? If yes-
i) What is it used for?
ii) How much space is reserved?

3- How should we interpret the USED and ALLOCATED column from the output of kubectl get cvr and kubectl get csp?

**Comment by mittachaitu** [comment]
Thanks @jj-2020, For sharing the output by testing on **sparse** & **non-sparse** files. I will interpret the above output(so if someone hits this issue it will be helpful).


**Sparse file**:

- fallocate will do preallocation quickly by allocating blocks and marking them as uninitialized. It will not push any IO to the data block due to this even if the underlying storage capacity is **15GB** we were able to do preallocate **900GB**. 

> [~]# kubectl get cvr -A
NAME USED ALLOCATED STATUS AGE
pvc-... 217M 5.85M Healthy 27m
pvc-... 258M 5.95M Healthy 27m

- Since fallocate is kind of thin provisioning it consumed only **5.85M** on the pool.

USED:  Amount of data written by the application filesystem on cStor volume(iSCSI disk).
ALLOCATED: Space consumed on the pool (I will provide links to docs later in this comment which will help to understand terms). 


**With non-sparse file**:

> Copied /var/log/messages file (2.2G) to the pod-
for i in {1..30};do kubectl cp /var/log/messages testapp-0-...:/home/app/test/messages_$i;done

In the above snippet since it performs IOs usage also increased(as shown below).

>Output of kubectl get cvr -A
[~]# kubectl get cvr
NAME USED ALLOCATED STATUS AGE
pvc-... 46.9G 14.1G Offline 40m
Note: Removed one entry for easy understanding

In the above, output USED capacity of CVR was **46.9GB**(i.e amount of data written by application filesystem).
Looks like pool capacity also almost full(Left **1.80GB** left out of **15.9G**). If you are using >= 2.0.0 version of OpenEBS then OpenEBS cStor pool might be went to RO mode(`kubectl describe csp <csp_name>` will show events).

In this case, ALLOCATED is **14.1G** compression, and deduplication of pool properties played a role over here.
.
.
.



**Now coming to questions part**:

> 1- Is there any document that we can refer, for the thick provisioning parameter in openebs?

I am not able to quickly find out the doc related to thickprovisioning but [this](https://github.com/openebs/maya/pull/1577) PR description will help to understand more.
**Note**: `overProvisioning` later converted to `thickProvisiong`  (Please replace the same while reading).


>2- We saw in the case of thick-provisioning and non-sparse files, the volume becomes read-only even though there is 1.80G free-
[~]# kubectl get csp
NAME ALLOCATED FREE CAPACITY STATUS READONLY TYPE AGE
cstor-disk-pool-1-... 14.1G 1.80G 15.9G Healthy true striped 52m

Yes, By default cStor allows to write up to **85%** of pool capacity(i.e threshold value) later that it will mark pool as ReadOnly means it will not allow further IOs. This [blog](https://openebs.io/blog/restricting-cstor-pool-usage-within-a-specified-threshold-value/) has a more detailed explanation of this read-only state.


>Is cstor reserving space? If yes-
i) What is it used for?
ii) How much space is reserved?

cStor is nothing but uZFS(userspace ZFS) it will reserve little data for pool metadata purposes this will be the same as how `ZFS pools` reserve. I am not pretty sure how it will calculate(Other folks can help here).

> 3- How should we interpret the USED and ALLOCATED column from the output of kubectl get cvr and kubectl get csp?

- This [blog](https://blog.mayadata.io/demystifying-disk-usage-in-cstor-pools) will help to understand cStor usage and terms.
- This [doc](https://docs.openebs.io/docs/next/cstor.html#cstor-pools) will help to understand the concepts of cStor terms(If interested).


Apart from the above, I would suggest using CSPC(CStor Pool Cluster) enhanced version of SPC. CSPC supports day-2-operations like (pool expansion, disk replacement, volume resize e.t.c...,). To understand more about CSPC click [here](https://github.com/openebs/cstor-operators#usage).

**Note**: CSPC doesn't have the option to support ThickProvisioning.

**Comment by pranav-shah294** [comment]
@mittachaitu 
From your last reply, I see CSPC is still into beta stage.
It would be helpful if you could let me know when will be the stable version released?

**Comment by jj-2020** [comment]
Thanks a lot @mittachaitu for the explanations/links, it cleared a lot our doubts. Currently, we too have the same concern regarding CSPC that was raised by @pranav-shah294, that being the reason why we explored spc instead of cspc.

**Comment by prateekpandey14** [comment]
@pranav-shah294 @jj-2020 thanks for trying openebs. CSPC is already stable, already used in production clusters by the openebs community users, we are working on the docs specific changes to update it as GA/Stable in coming releases, and deprecate the SPC from the 3.x release onwards.

**Comment by abhiTamrakar** [comment]
@prateekpandey14 my question may not be related to this but might be important to consider, do we have a version of kubernetes where openebs stable is last tested?

**Comment by prateekpandey14** [comment]
@abhiTamrakar OpenEBS latest release v2.8.0 (released on 16th April) has a minimum k8s requirement of 1.18+ k8s version ,  since the k8s has deprecated various beta apis and suggested to migrate to k8s V1 apis for all the CRDs and in-tree APIs.

| Openebs Version | Minimum K8s Version |
------------------------ | ------------------------------
| v2.7.0 | 1.17+|
v2.8.0 | 1.18+|

We recommend to use atleast 1.18+ k8s version

**Comment by jj-2020** [comment]
> Hi @jj-2020, Thanks for trying out OpenEBS... Before getting into the issue I would like to mention a few points:
> 
> * By default OpenEBS cStor supports thin provisioning of Volumes(We can enable thick provisioning by setting true in [thickProvisioning](https://github.com/openebs/openebs/blob/7b390d39515a288327ae68020745884de59f83bf/k8s/ci/overprovisioning/overprovisioning-disabled-sparse-pool.yaml#L14) field).
> * Thick provision will prevent creating volumes larger than underlying pool capacity.
> 
> Now coming back to the issue:
> 
> * Since the application volume is requested for 1TB it allowed the creation of volume(cStor by default supports thin provisioning).
> * cStor pool has by default enabled the following properties compression & deduplication due to this if the application dumps the same data it might be compressed(but here, it is a bit strange it compressed ` 401G` to `18.3M `).
> 
> Could you help with the following outputs(Which may help to understand the issue further)?
> 
> * kubectl get cvr -A
> * kubectl get pv
> * Is load really generated the load? (Or) Do you create the sparse files?
> * Can you share `du -sh` running inside the container?

@mittachaitu , is there a way to disable compression and de-duplication of data in cstor?
Currently trying out the cstor-operator.

**Comment by prateekpandey14** [comment]
@jj-2020 you can update the [compression field](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/cspc/tuning/tune.md#compression) in CSPC object  as `compression: off` and apply it, to disable the compression on pool.

**Comment by prateekpandey14** [comment]
Closing this , please feel free to reopen if required.
