### ISSUE TITLE
Admission controller to auto create or patch CStorPoolCluster upon addition of new cluster nodes

### ISSUE THREAD

**Issue by reggie-k** [openebs/openebs#3430]
## Description
Currently, the CStorPoolCluster needs to be created and patched manually upon addition of new nodes/block devices.

Does some admission controller to automate this process exist / is being planned?

**Comment by mittachaitu** [comment]
Hi @reggie-k, Thanks for opening an issue. Since a single cluster can accumulate multiple CStorPoolClusters a use case where users can create different type of CStorPoolClusters based on the type of the disk HDD/SSD and lot of other various factors. Waiting for new nodes/bd's and acting upon them is a good one to have but the admission server is not the right place. 

We can achieve the same via [openebsctl](https://github.com/openebs/openebsctl)
- To make life easy we can trigger a command using [openebsctl](https://github.com/openebs/openebsctl) and it will help with new yaml/itself will apply based on sub-commands(**Not yet available**). Something like https://github.com/openebs/openebsctl
- Another way will be writing operator on top of CSPC which will automate the process base on some configuration.
