### ISSUE TITLE
Kyverno policies for OpenEBS 

### ISSUE THREAD

**Issue by nareshdesh** [openebs/openebs#3443]
## Description
On a Kubernetes clusters with kyverno policies(baseline or restricted) enabled, openebs deployment is failing 

### Restricted policy
Kyverno installation
```
helm install kyverno kyverno/kyverno --namespace kyverno --create-namespace --set podSecurityStandard=restricted --set validationFailureAction=enforce

NAME: kyverno
LAST DEPLOYED: Wed Sep 22 18:59:19 2021
NAMESPACE: kyverno
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing kyverno v2.0.3 😀

Your release is named kyverno, app version v1.4.3

We have installed the "restricted" profile of Pod Security Standards and set them in enforce mode.

Visit https://kyverno.io/policies/ to find more sample policies.
```

OpenEBS deployment
```
helm install openebs openebs/openebs --namespace openebs --create-namespace --set legacy.enabled=false --set cstor.enabled=true --set openebs-ndm.enabled=true --set rbac.kyvernoEnabled=true

Error: admission webhook "validate.kyverno.svc" denied the request:

resource DaemonSet/openebs/openebs-ndm was blocked due to the following policies

disallow-host-namespaces:
  autogen-host-namespaces: 'validation error: Sharing the host namespaces is disallowed.
    The fields spec.hostNetwork, spec.hostIPC, and spec.hostPID must not be set to
    true. Rule autogen-host-namespaces failed at path /spec/template/spec/hostNetwork/'
disallow-host-path:
  autogen-host-path: 'validation error: HostPath volumes are forbidden. The fields
    spec.volumes[*].hostPath must not be set. Rule autogen-host-path failed at path
    /spec/template/spec/volumes/1/hostPath/'
disallow-privileged-containers:
  autogen-priviledged-containers: 'validation error: Privileged mode is disallowed.
    The fields spec.containers[*].securityContext.privileged and spec.initContainers[*].securityContext.privileged
    must not be set to true. Rule autogen-priviledged-containers failed at path /spec/template/spec/containers/0/securityContext/privileged/'
require-run-as-non-root:
  autogen-check-containers: 'validation error: Running as root is not allowed. The
    fields spec.securityContext.runAsNonRoot, spec.containers[*].securityContext.runAsNonRoot,
    and spec.initContainers[*].securityContext.runAsNonRoot must be `true`. Rule autogen-check-containers[0]
    failed at path /spec/template/spec/securityContext/runAsNonRoot/. Rule autogen-check-containers[1]
    failed at path /spec/template/spec/containers/0/securityContext/runAsNonRoot/.'
```
### Baseline policy
kyverno deployment
```
helm install kyverno kyverno/kyverno --namespace kyverno --create-namespace --set podSecurityStandard=baseline --set validationFailureAction=enforce

NAME: kyverno
LAST DEPLOYED: Wed Sep 22 19:28:05 2021
NAMESPACE: kyverno
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing kyverno v2.0.3 😀

Your release is named kyverno, app version v1.4.3

We have installed the "baseline" profile of Pod Security Standards and set them in enforce mode.

Visit https://kyverno.io/policies/ to find more sample policies.
```
OpenEBS deployment
```
 helm install openebs openebs/openebs --namespace openebs --create-namespace --set legacy.enabled=false --set cstor.enabled=true --set openebs-ndm.enabled=true

Error: admission webhook "validate.kyverno.svc" denied the request:

resource DaemonSet/openebs/openebs-ndm was blocked due to the following policies

disallow-host-namespaces:
  autogen-host-namespaces: 'validation error: Sharing the host namespaces is disallowed.
    The fields spec.hostNetwork, spec.hostIPC, and spec.hostPID must not be set to
    true. Rule autogen-host-namespaces failed at path /spec/template/spec/hostNetwork/'
disallow-host-path:
  autogen-host-path: 'validation error: HostPath volumes are forbidden. The fields
    spec.volumes[*].hostPath must not be set. Rule autogen-host-path failed at path
    /spec/template/spec/volumes/1/hostPath/'
disallow-privileged-containers:
  autogen-priviledged-containers: 'validation error: Privileged mode is disallowed.
    The fields spec.containers[*].securityContext.privileged and spec.initContainers[*].securityContext.privileged
    must not be set to true. Rule autogen-priviledged-containers failed at path /spec/template/spec/containers/0/securityContext/privileged/'
```

## Expected Behavior
OpenEBS deployment with the `rbac.kyverno` enabled, it should have set the policies, which would have deployed openebs successfully.  

## Your Environment
* Others:
GKE cluster with v1.20.9

**Comment by kmova** [comment]
@Nivedita-coder can you please check on this one?

**Comment by Nivedita-coder** [comment]
Hey @nareshdesh,
You had installed the kyverno with a restricted and baseline flag, that's why it has blocked the deployment of OpenEBS. Baseline and Restricted come under  Pod Security Standards. For more details, regarding this, you can check this [blog](https://dev.to/niveditacoder/default-kyverno-policies-for-openebs-4abf).

Here are the steps:
1. Install the kyverno in the Kubernetes cluster using YAMLs
`kubectl create -f https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml`
 or via [helm](https://kyverno.io/docs/installation/#install-kyverno-using-helm)
2. After that install OpenEBS.
`helm install openebs openebs/openebs --namespace openebs --create-namespace --set legacy.enabled=false --set cstor.enabled=true --set openebs-ndm.enabled=true --set rbac.kyvernoEnabled=true`

Now, it'll work.
Thanks!

**Comment by nareshdesh** [comment]
@Nivedita-coder,  what if an administrator has set these policies i.e Baseline or Restricted at a cluster scope. What additional policies does OpenEBS needs to set, in order for the openebs deployment to work.

As per the steps mentioned above, the OpenEBS deployment works even if we do not set  `rbac.kyvernoEnabled=true`
i.e 
1. Install the kyverno in the Kubernetes cluster using YAMLs
`kubectl create -f https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml
or via helm.`
1. After that install OpenEBS.
`helm install openebs openebs/openebs --namespace openebs --create-namespace --set legacy.enabled=false --set cstor.enabled=true --set openebs-ndm.enabled=true` 

With the above behavior, it is not sure whether the openebs policy created, were making any difference at all

**Comment by Nivedita-coder** [comment]
Hey @nareshdesh,
If an administrator will set the policies either baseline or restricted at cluster or namespace level. Then deployment of OpennEBS will not be possible because it blocks the creation of NDM and NDM is an important component in OpenEBS architecture. For that reason, we have written our custom policies with some additional features.

1. Installed Kyverno in the cluster
`kubectl create -f <https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml`>
2. After that install OpenEBS with `rbac.kyvernoEnabled=true` then check `kubectl get pol` you will get openebs policy list that has been created.

But if you install OpenEBS without `rbac.kyvernoEnabled=true` then you'll find an empty policy list. So, by using `kubectl get pol` we can check that whether the policy has been created or not.

**Comment by pawanpraka1** [comment]
Closing this issue, Please reopen it if you are still facing the issue.
