### ISSUE TITLE
4.0.1 kubectl mayastor upgrade job failed if 'mayastor.loki-stack.enabled=false'

### ISSUE THREAD

**Issue by AleksandrSor** [openebs/openebs#3720]
## Description
helmchart installed with --set 'mayastor.loki-stack.enabled=false'
when you run 
```
kubectl mayastor upgrade -n openebs --set 'mayastor.agents.core.rebuild.partial.enabled=false'
```
you got upgrade job pod crashed with
```
: mayastor.loki-stack.loki: missing field `image` at line 745 column 7
    at k8s/upgrade/src/bin/upgrade-job/main.rs:34
```

## Expected Behavior
upgrade job completed successfully

## Current Behavior
upgrade job crashed

## Possible Solution
temporary enable loki stack with --set 'mayastor.loki-stack.enabled=true'
and then upgrade mayastor

## Steps to Reproduce
1. helm chart upgraded from 3.9.0 to 4.0.1 as in instruction
2. values.yaml
```
mayastor:
  enabled: true
  loki-stack:
    enabled: false
```
3. run 
```
kubectl mayastor upgrade -n openebs --set 'mayastor.agents.core.rebuild.partial.enabled=false'
```
4. got an error in the job pod

## Your Environment
* OS (from `/etc/os-release`):
```
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream
```
* Kernel (from `uname -a`): Linux k8host-lon04.l8s.space 5.14.0-437.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Apr 9 12:57:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Install tools:
```
kubectl 1.29.4
mayastor plugin 2.6.1
```

**Comment by niladrih** [comment]
Hi @AleksandrSor, this does seem to happen with installations done with helm v3.13 and above. I've created an issue with helm https://github.com/helm/helm/issues/12936. However, this does seem like this is intentional on helm's side. I'll track this issue here and try to come up with a solution for this.

A quick fix for this will be setting the serde_yaml Deserialize to use 'default' values when loki-stack is disabled, e.g. how this PR does it for some other dependency chart values: https://github.com/openebs/mayastor-extensions/pull/479.

**Comment by orville-wright** [comment]
A PR in mayastor-extensions has been raised by @niladrih & has been successfully merged. It implements the Deserialize fix.
- https://github.com/openebs/mayastor-extensions/pull/512

Closing issue
