### ISSUE TITLE
Add Documentation for prometheus

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#390]
## Documentation
* Add Readme and documentation related to prometheus.

**Comment by AmitKumarDas** [comment]
### Quotes on Prometheus from various References:

- Prometheus is **not** an `event-based monitoring system`. 
  - You do not send raw events to Prometheus, nor can it store them. Prometheus is in the business of collecting aggregated time series data.

- The effort for establishing a connection is small compared to the metrics payload and other required work. The `TCP/HTTP overhead in Prometheus` is still **negligible** compared to the other work that the Prometheus server has to do to ingest data (especially persisting time series data on disk).

- The scaling bottleneck here has never been related to pulling metrics, but usually to the speed at which the Prometheus server can ingest the data into memory and then sustainably persist and expire data on disk/SSD.

- When you have many endpoints scattered around the world which are not directly reachable due to firewalls or complicated networking setups, and where it's infeasible to run a Prometheus server directly in each of the network segments. This is not quite the environment for which Prometheus was built, although workarounds are often possible (via the [Pushgateway](https://prometheus.io/docs/practices/pushing/) or restructuring your setup).

- How to feed logs into Prometheus? 
  - Don't. Use ELK for this instead. Prometheus is a system to collect and process metrics, not an event logging system. The Raintank blog post [Logs and Metrics and Graphs, Oh My!](https://grafana.com/blog/2016/01/05/logs-and-metrics-and-graphs-oh-my/) provides more details about the differences between logs and metrics.

- If you want to extract Prometheus metrics from application logs, Google's mtail might be helpful.

- Can I send Alerts ? Yes. With Alertmanager.

- How is Prometheus highly available ?  Run identical Prometheus servers on two or more separate machines. Identical alerts will be deduplicated by the [Alertmanager](https://github.com/prometheus/alertmanager). For [high availability](https://github.com/prometheus/alertmanager#high-availability) of the Alertmanager, you can run multiple instances in a [Mesh cluster](https://github.com/weaveworks/mesh) and configure the Prometheus servers to send notifications to each of them.

- Why does Prometheus use a custom storage backend rather than [some other storage method]? Isn't the "one file per time series" approach killing performance?
  - Initially, Prometheus ran completely on LevelDB, but to achieve better performance, we had to change the storage for bulk sample data. We evaluated many storage backends that were available at the time, without getting satisfactory results. So we implemented exactly the parts we needed.
  - For indexes, it uses [LevelDB](https://github.com/google/leveldb) 
  - For the bulk sample data, it has its own custom storage layer, which organizes sample data in chunks of constant size (1024 bytes payload). These chunks are then stored on disk in one file per time series.
  - LevelDB for making heavy use of file system capabilities.
  - More on chunks & chunk encodings are present [here](https://prometheus.io/docs/operating/storage/) & [here](https://prometheus.io/blog/2016/05/08/when-to-use-varbit-chunks/).

- What about the memory usage of this custom storage backend ?
  - Prometheus keeps all the currently used chunks in memory. In addition, it keeps as many most recently used chunks in memory as possible. You have to tell Prometheus how much memory it may use for this caching.
  - Details are available [here](https://prometheus.io/docs/operating/storage/).

- What about the performance local storage solution for most of the use-cases ?
  - Important requirements are:
    - An acceptable query speed for common queries &
    - Sustainable ingestion rate of hundreds of thousands of samples per second. This further depends on many parameters, like the compressibility of the sample data, the number of time series the samples belong to, the retention policy, and even more subtle aspects like how full your SSD is.
  - Refer [configuring prometheus for performance](https://www.youtube.com/watch?v=hPC60ldCGm8).

- InfluxDB vs. Prometheus:
  - InfluxDB uses a variant of a [log-structured merge tree for storage with a write ahead log](https://docs.influxdata.com/influxdb/v1.2/concepts/storage_engine/), sharded by time. This is much more suitable to event logging than Prometheus's append-only file per time series approach. InfluxDB supports timestamps with up to nanosecond resolution, and float64, int64, bool, and string data types. Prometheus by contrast supports the float64 data type with limited support for strings, and millisecond resolution timestamps.
  - InfluxDB is maintained by a single commercial company following the open-core model, offering premium features like closed-source clustering, hosting and support. Prometheus is a fully open source and independent project, maintained by a number of companies and individuals, some of whom also offer commercial services and support.

- InfluxDb is better when:
  - You are doing event logging
  - Commercial option offers clustering for InfluxDB, which is also better for long term data storage.
  - Eventually consistent view of data between replicas.

- What about Prometheus' Query Language ?
  - It is a [query language used for graphing & alerting](https://www.robustperception.io/translating-between-monitoring-languages/).

### References:

- https://prometheus.io/blog/2016/07/23/pull-does-not-scale-or-does-it/
