### ISSUE TITLE
Use only type Volume in types.go and deprecate other redundant Volume types

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#420]
#

## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

### Details

- Use only `type Volume`
- Other related volume types should be deprecated & removed

- Refer: https://github.com/openebs/maya/blob/master/types/v1/types.go

### Notes

- This might break other maya components who are interfacing each other
  - Create respective issues for each component in these cases

**Comment by kmova** [comment]
PersistentVolume and PersistentVolumeClaim have a close resemblance with K8s concepts and it is very easy to get it confused. And it gets more confusing, since OpenEBS Volume inturn uses PV and PVCs for exposing an OpenEBS Volume. 

It may be less confusing if, we use the terms OpenEBSVolume or just Volume, for referring to OpenEBS Volumes.  @AmitKumarDas -- your comments?

**Comment by AmitKumarDas** [comment]
Volume is the term we should go with.
It should reflect a K8s Deployment minus the un-necessary properties if possible.

**Comment by prateekpandey14** [comment]
Create a single `volume` struct which will be used as follows:
1. Same struct is going to use for` request` and `response` for a creating a volume and so forth
which will contains all the CRUD operation related  to volume.
(struct fields can be used/filled  based on the operation is going to be performed)
2. List  volumes (complaint to deployments or statefulset) will be using this `volume` struct.
( need to explore towards statefulset and deloyments side ) , how can we use them in our single struct.
