### ISSUE TITLE
Support "ReadOnlyMany" access mode for OpenEBS volumes. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#439]
K8s supports using the following three access modes for PersistentVolumes:
- ReadWriteOnce (supported by OpenEBS)
- ReadOnlyMany
- ReadWriteMany
(ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/)

This issue is raised to track how to use ReadOnlyMany with OpenEBS Volumes:
- Does this only require changes to the openebs-k8s-provisioner or is there some new code that needs to be added to the storage controller (jiva)
- What are the use-cases (applications) in which this feature can come useful

**Comment by clkao** [comment]
Were there any findings about what implementing ReadOnlyMany involves?

**Comment by josdotso** [comment]
Was asked about this today.  GlusterFS apparently supports it.

**Comment by kmova** [comment]
@josdotso @clkao - Went ahead with the approach of supporting RWM via the use of nfs provisioner on top of iSCSI block volume. More details can be found at: https://docs.openebs.io/docs/next/rwm.html

**Comment by vinerich** [comment]
### Possible use case

We currently evaluate using OpenEBS as a backing store for a distributed processing system running in kubernetes. In short we have worker pods that are scheduled with different configurations depending on the job.

One part of the configuration includes dynamic plugins which are written into a freshly (per-job) created distributed PV and should then be accessible by **every worker pod on each node (!)**.

Currently all worker pods need to be scheduled on **one node (!)** since only `ReadWriteOnce` is supported. Surely I can implement the nfs provisioner on top (https://docs.openebs.io/docs/next/rwm.html), but since the data is already replicated to each node (distributed PV) logically this doesn't sound like the best solution (performance- and traffic-wise) to me.

I'd vote for an implementation of `ROM`, but also I don't have the expertise to guess the implementation cost.
Thanks for your time reading this!
