### ISSUE TITLE
Expose REST APIs to backup and restore jiva snapshots to S3

### ISSUE THREAD

**Issue by payes** [openebs/openebs#535]
FEATURE REQUEST

**Why is this required ?**
The original method of backing up the snapshot to S3 is not practical. It does an exec to the container and runs the CLI command which might not be possible in most scenarios.

**How to do it ?**
A REST API needs to be added to the original list and the functions called in BackupCmd can be used as help. 
[https://github.com/openebs/jiva/wiki/Cli-Commands](url)

**Comment by kmova** [comment]
related to : https://github.com/openebs/openebs/issues/98

**Comment by khushbuparakh** [comment]
Hi I am picking up this isseu.

**Comment by ashishranjan738** [comment]
go ahead @khushbuparakh . Let me know if you need any help.

**Comment by kmova** [comment]
Currently, the preferred approach to Backup/Restore of Jiva Volumes to S3 is via Velero. https://github.com/heptio/velero

The documentation is available at : https://docs.openebs.io/docs/next/backup.html

This issue is kept open in case there is interest in trying to use a direct approach for Backup and Restore from Jiva itself.
