### ISSUE TITLE
Automated bot for managing GitHub issue/pull request life-cycle

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#644]
The process followed for submitting PRs, Reviewing and Merging them are detailed at https://github.com/openebs/openebs/issues/213. The current process involves several manual steps (some examples below), that can be automated using a bot:
- Verify that pull requests follows the template - which at the minimum mentions the issue being fixed
- Assigning the size label to the submitted PRs depending on the code changes
- Assigning the status labels or clearing them when PR is merged

**Comment by vharsh** [comment]
There seems to be a lot of shiny new stuff at GitHub marketplace besides actions. I'll update this post with things I find useful.

## Free solutions for GitHub issue management
1. Issue label bot labels issues as `bug` or `feature`. It might be really helpful as it doesn't seem to require a lot of configs. It does support label aliases.
It might not be very helpful because we have separate issue templates for bug & a feature, but they do not label the created issue. This is where I miss the `/label bug` from k8s
Ref: https://github.com/marketplace/issue-label-bot

2. This PR labeler picks up things from the branch-name 
Ref: https://github.com/marketplace/actions/pr-labeler

3. This one does things based on the PR title.
https://github.com/marketplace/actions/condition-based-pull-request-labeler

4. Who needs to approve this PR?
Ref: https://github.com/marketplace/pullapprove

None of these solutions seem to fit our use cases completely, we might want to write our own GitHub actions or use two or three of these tools.
