### ISSUE TITLE
Testing Percona Galera Cluster Usecase Documentation

### ISSUE THREAD

**Issue by mahebbar** [openebs/openebs#920]
Choose one: TESTING

**What happened**: Documentation must be tested for 0.5

**What you expected to happen**: Check if the documentation procedure works fine.

**Comment by nsathyaseelan** [comment]
- In Deploying the Percona Galera Cluster with OpenEBS Storage documentation the steps mentioned and it will mention the command `ls -ltr` it will not shows any files like in documentation
- Wait until the pxc-node1 YAML is processed and repeat the step with pxc-node2 and pxc-node3 YAMLs. In this step how will i know pxc-node1 YAML is finished its process or not and how long it will take to complete
- Change the following sentence because there is no URL given here
```
OpenEBS recommends creating the Galera cluster with at least 3 nodes/replicas. Go to the following URL for details
```
